global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: collector
    scrape_protocols: [OpenMetricsText1.0.0, OpenMetricsText0.0.1, PrometheusText0.0.4]
    static_configs:
      - targets: [collector:8889]
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
